### ISSUE TITLE
Options order?

### ISSUE THREAD

**Issue by arturekdev** [A248/DazzleConf#19]
How to set options order?

**Comment by A248** [comment]
### Using annotations

You can use AnnotationBasedSorter to sort your configuration by `@Order` annotations.

First add `@Order` to each configuration entry:

```java
public interface MyConfig {

  @Order(10)
  @DefaultInteger(0)
  int entryOne();

  @Order(20)
  @DefaultString("str")
  String entryTwo();
}
```

Then add AnnotationBasedSorter to your ConfigurationOptions, and add the options to your ConfigurationFactory.
```java
ConfigurationOptions options = new ConfigurationOptions.Builder().sorter(new AnnotationBasedSorter()).build();
```

If you are following the example from the wiki, replace `ConfigurationOptions.defaults()` with the options here.

### Using another way to order your configuration

Implement a ConfigurationSorter, and add it to your ConfigurationOptions just like you would with AnnotationBasedSorter.

**Comment by A248** [comment]
I've now added a wiki page about this (it has the same content)

**Comment by arturekdev** [comment]
Thanks for help <3
