### ISSUE TITLE
Recursive Serializer

### ISSUE THREAD

**Issue by superyuuki** [A248/DazzleConf#29]
Implement a ValueSerializer that deserializes interfaces similar to the core behavior of DazzleConf: Simply provide it an interface class and it will deserialize it using any values annotated on the object.

**Comment by gepron1x** [comment]
But what about serializing? Configuration objects are immutable theirself. Thats gonna look strange if you deserialize your Object with type-safe interfaces and serializing it with regular map.

**Comment by A248** [comment]
This already exists: `@SubSection`

```java
public interface MyConfig {

  @ConfKey("sub-section")
  @SubSection
  MySubSection subSection();

  interface MySubSection {
    
    @DefaultBoolean(false)
    boolean toggle();
  
    @DefaultString("hooray")
    String message();
  }
}
```

> Thats gonna look strange if you deserialize your Object with type-safe interfaces and serializing it with regular map.

We essentially re-build the map by deserializing the options in the configuration instance. For example, the serialized representation of `MySubSection` in the example above, using default values, is equivalent to `Map.of("toggle", false, "message", "hooray")` - a `Map<String, Object>`.

**Comment by superyuuki** [comment]
Oh, i meant a standalone `ValueSerializer`. Already saw the SubSection, I depend on it. This new `ValueSerializer` is important since you may want to invoke it from another `ValueSerializer` from `FlexibleType`.

**Comment by A248** [comment]
Yes, this looks like an XY problem.

**Comment by gepron1x** [comment]
Just use flexibleType.getObject(Class)? it will find a serializer for you.

**Comment by superyuuki** [comment]
@gepron1x Not for dynamically created interfaces...
