### ISSUE TITLE
More flexible comments support

### ISSUE THREAD

**Issue by A248** [A248/DazzleConf#3]
Allow adding empty lines and different styles of comments.

**Comment by CDFN** [comment]
What do you mean with `different style of comments?` Could you extend?

**Comment by A248** [comment]
I'm referring to how SnakeYamlConfigurationFactory adds a space before and after the '#'. This is what it does presently:

```java
			StringBuilder commentBuilder = new StringBuilder(depthPrefix);
			commentBuilder.append(" # ").append(comment).append('\n');
			writer.append(commentBuilder);
```

BlueTree asked me if it would be possible to skip one or both of those spaces.

**Comment by CDFN** [comment]
What would you think about setting comment "pattern"? E.g. `# somePrefix %s` where %s is actual comment. Each comment would get created using this pattern.

**Comment by A248** [comment]
That sounds like a good idea. It could be added to SnakeYamlOptions in a compatible manner.

Do you know an effective way to validate a String.format format? I would presume calling String.format with some dummy string argument is sufficient, e.g.:

```java
public Builder commentPattern(String format) {
  try {
    String.format(format, "dummy");
  } catch (IllegalFormatException ex) {
     throw new IllegalArgumentException(ex); // or just rethrow
  }
  this.format = format;
  return this;
}
```

**Comment by CDFN** [comment]
Your solution doesn't seem bad for me. I'd just rethrow though.

**Comment by A248** [comment]
Done in https://github.com/A248/DazzleConf/commit/3cbe2b88b17a031064c0f877b1a99586215be899

Will be added to 1.2.0-SNAPSHOT and ultimately 1.2.0 release
